services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=carpartsdb
      - POSTGRES_USER=dbuser
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA="/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
      - carpartsdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d carpartsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  app-backend:
    image: app-backend
    build:
      context: ./carparts-backend
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
        - PORT=80
    environment:
      - PORT=80
    ports:
      - "4000:80"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  app-frontend:
    image: app-frontend
    build:
      context: ./carparts-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - app-backend
    restart: unless-stopped
  
volumes:
  carpartsdb-data:
